# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: "{name: \"趙勗博\"}"
title: '{Chris Chao: "blogging"}'
email: chaoshubo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  程式設計，網頁設計，學習筆記，讀書心得...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shuboc.github.io" # the base hostname & protocol for your site
twitter_username: apiggy0204
github_username:  shuboc
facebook_username: chris.chao.10

# Build settings
markdown: kramdown
