# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: "{name: \"趙勗博\"}"
title: "Shubo's Notes"
email: shubochao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shubo的程式設計教學、書籍推薦、心得分享。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shubo.io" # the base hostname & protocol for your site
permalink: /:categories/:title/

twitter:
  username: apiggy0204
social:
  name: Shubo Chao
  links:
    - https://twitter.com/apiggy0204
    - https://www.facebook.com/chris.chao.10
    - https://www.linkedin.com/in/shubo-chao-a0a97a8b/
    - https://github.com/shuboc

twitter_username: apiggy0204
github_username:  shuboc
facebook_username: chris.chao.10
linkedin_username: shubo-chao-a0a97a8b

# Build settings
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "shubo"
