# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shubo's Tech Blog
email: shubochao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! I am Shubo Chao (趙勗博), and this is my tech blog!
  I'd like to share cool things about web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shuboc.github.io" # the base hostname & protocol for your site
twitter_username: apiggy0204
github_username:  shuboc

# Build settings
markdown: kramdown
