# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: "{name: \"趙勗博\"}"
title: '{"Shubo": "Programming Notes"}'
email: shubochao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  趙勗博的程式技術筆記，主題涵蓋前端開發（JavaScript、CSS、HTML)、演算法等，歡迎同好留言分享交流( ͡° ͜ʖ ͡°)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shubo.io" # the base hostname & protocol for your site
twitter_username: apiggy0204
github_username:  shuboc
facebook_username: chris.chao.10

# Build settings
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "shubo"
